export { default as Home } from "./Home";
export { default as List } from "./ListPokemon";
export { default as Team } from "./Team";
export { default as Footer } from "./Footer";
export { default as Navbar } from "./Navbar";
export { default as SignIn } from './SignIn'
export { default as SignUp } from './SignUp'
export { default as ListPokemon } from './ListPokemon'
export { default as DetailPokemon } from './DetailPokemon'
